### ISSUE TITLE
Tag "alt" on UML is mandatory on local store

### ISSUE THREAD

**Issue by Chklang** [artifacthealth/typedoc-plantuml#1]
Hi

After some hours of problems i've found this bug.

If your comment is :
```
     * <uml>
     *     Bob->Alice : hello
     * </uml>
```
So the generation by typedoc will done :
`<img src="http://www.plantuml.com/plantuml/png/UDhZKW02f_maNJl7dCpaL0KhXOpKd9nyBW17hWP_" alt="">`

So the regexp :
`encodedUmlExpression = /<img src="http:\/\/www.plantuml.com\/plantuml\/(?:img|png|svg)\/([^"]*)"(?: alt="(.+)")?>/g,`

don't work because "alt" attribut is empty.

**Comment by meirgottlieb** [comment]
Nice catch. I just pushed a new version to NPM that fixes this bug.

**Comment by Chklang** [comment]
Great!

Very very reactive!
