### ISSUE TITLE
Problem if diagram is too big

### ISSUE THREAD

**Issue by Chklang** [artifacthealth/typedoc-plantuml#3]
Hi

First : Bravo for your reactive!

This morning i've tried to realize complex diagrams and i've a bug. If the diagram is too big so diagram go out of his area. You can see it :
![bug_typedoc_plantuml_01](https://cloud.githubusercontent.com/assets/3867590/13456029/3be9dfc2-e061-11e5-8d9e-0c47ebcc4cd0.jpg)

So maybe we can add a style="max-width: 100%" at the img tag?

Regards.

**Comment by meirgottlieb** [comment]
The plugin now appends .uml { max-width: 100%; } to the main.css file.
