### ISSUE TITLE
Problem with property umlLocaltion since 1.4.x

### ISSUE THREAD

**Issue by Chklang** [artifacthealth/typedoc-plantuml#5]
Hi

Since last day we have this error into build :

> [09:57:57] The plugin typedoc-plantuml could not be loaded.
> [09:57:57] Unknown option: umlLocation

Us configuration is :

```
.pipe(typedoc({
	module               : "commonjs",
	target               : "es5",
	out                  : dest,
	excludeExternals     : true,
	ignoreCompilerErrors : true,
	mode                 : 'file',
	name                 : name,
	readme: readme ? readme : 'README.md',
	umlLocation          : 'remote'
}))

```
What we must do to be compatible with 1.4.x of typedoc-plantuml?

Thanks

**Comment by meirgottlieb** [comment]
What version of TypeDoc are you using? The latest version of typedoc-plantuml requires TypeDoc 0.4.1. The plugin architecture in TypeDoc was changed significantly in the latest version and typedoc-plantuml 1.4.x was updated to be compatible with the latest version of TypeDoc.

**Comment by Chklang** [comment]
Extract from node_modules/typedoc :
```
{
  "name": "typedoc",
  "description": "Create api documentations for typescript projects.",
  "version": "0.4.1",
  "homepage": "http://typedoc.io",
  ...
```

**Comment by meirgottlieb** [comment]
It looks like you are using gulp-typedoc. What version of that are you using?

**Comment by meirgottlieb** [comment]
Update to the latest version of gulp-typedoc, 2.0.0. The version you are on has a dependency on a specific version of TypeDoc so it's actually not using 0.4.1. The newer version of gulp-typedoc uses a peer dependency so it will use the latest version of TypeDoc that you have installed.

**Comment by Chklang** [comment]
Great! It's works with gulp-typedoc ^2.0.0

Thanks for your help!

**Comment by meirgottlieb** [comment]
Your welcome.
