### ISSUE TITLE
Project Health?

### ISSUE THREAD

**Issue by kferrone** [artifacthealth/typedoc-plantuml#7]
So no commits since 2016?? Any chance there can be some updates and make it work with the latest and greatest. 

I did at least find this fork: https://github.com/0815fox/typedoc-plantuml
Maybe see if you can update using their repo code. Maybe ask them to submit PR. 

If this project is literally done and dead, please remove from npm so @0815fox could add their more up to date version.

**Comment by 0815fox** [comment]
Well... more up to date but I did not spend any time on this anymore, because I stopped using it myself, actually because I changed my job. Fell free to fork and take over my work and eventually publish on npm when the name gets freed.

**Comment by meirgottlieb** [comment]
Hey @kferrone. This project is not dead. I still use regularly with the older version of Typedoc. I have not had a need to upgrade Typedoc, and so have not updated this project. I'm happy to accept a PR if you would like to update it to work with the latest Typedoc.

I do not plan on removing from NPM, as I still use this regularly. Other parties can publish to NPM under a different name if they like.
